#!/usr/bin/env bash
# Tags: no-fasttest
# Tag no-fasttest -- uses an interserver-secret cluster

CURDIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
# shellcheck source=../shell_config.sh
. "$CURDIR"/../shell_config.sh

# Verify that SET ROLE on the initiator is honoured on the remote node of a
# Distributed read over an interserver-secret cluster.

USER="test_04498_${CLICKHOUSE_DATABASE}"
ROLE_NARROW="role_narrow_04498_${CLICKHOUSE_DATABASE}"
ROLE_ADMIN="role_admin_04498_${CLICKHOUSE_DATABASE}"

${CLICKHOUSE_CLIENT} -q "DROP TABLE IF EXISTS ${CLICKHOUSE_DATABASE}.local_04498"
${CLICKHOUSE_CLIENT} -q "DROP TABLE IF EXISTS ${CLICKHOUSE_DATABASE}.dist_04498"
${CLICKHOUSE_CLIENT} -q "DROP ROW POLICY IF EXISTS pol_narrow_04498 ON ${CLICKHOUSE_DATABASE}.local_04498"
${CLICKHOUSE_CLIENT} -q "DROP ROW POLICY IF EXISTS pol_admin_04498 ON ${CLICKHOUSE_DATABASE}.local_04498"
${CLICKHOUSE_CLIENT} -q "DROP ROLE IF EXISTS ${ROLE_NARROW}"
${CLICKHOUSE_CLIENT} -q "DROP ROLE IF EXISTS ${ROLE_ADMIN}"
${CLICKHOUSE_CLIENT} -q "DROP USER IF EXISTS ${USER}"

${CLICKHOUSE_CLIENT} -q "CREATE TABLE ${CLICKHOUSE_DATABASE}.local_04498 (x UInt32) ENGINE = MergeTree ORDER BY x"
${CLICKHOUSE_CLIENT} -q "INSERT INTO ${CLICKHOUSE_DATABASE}.local_04498 VALUES (1),(2),(3),(4),(5)"

${CLICKHOUSE_CLIENT} -q "CREATE TABLE ${CLICKHOUSE_DATABASE}.dist_04498 AS ${CLICKHOUSE_DATABASE}.local_04498 ENGINE = Distributed('test_cluster_interserver_secret', '${CLICKHOUSE_DATABASE}', 'local_04498')"

${CLICKHOUSE_CLIENT} -q "CREATE ROLE ${ROLE_NARROW}"
${CLICKHOUSE_CLIENT} -q "CREATE ROLE ${ROLE_ADMIN}"
${CLICKHOUSE_CLIENT} -q "CREATE USER ${USER} DEFAULT ROLE ${ROLE_NARROW}, ${ROLE_ADMIN}"
${CLICKHOUSE_CLIENT} -q "GRANT SELECT ON ${CLICKHOUSE_DATABASE}.* TO ${ROLE_NARROW}, ${ROLE_ADMIN}"
${CLICKHOUSE_CLIENT} -q "GRANT REMOTE ON *.* TO ${ROLE_NARROW}, ${ROLE_ADMIN}"
${CLICKHOUSE_CLIENT} -q "CREATE ROW POLICY pol_narrow_04498 ON ${CLICKHOUSE_DATABASE}.local_04498 FOR SELECT USING x <= 2 TO ${ROLE_NARROW}"
${CLICKHOUSE_CLIENT} -q "CREATE ROW POLICY pol_admin_04498  ON ${CLICKHOUSE_DATABASE}.local_04498 FOR SELECT USING 1 TO ${ROLE_ADMIN}"

# With role_narrow the remote node should only see rows where x <= 2.
echo "-- role_narrow via Distributed"
${CLICKHOUSE_CLIENT} --user "${USER}" -q "SET ROLE ${ROLE_NARROW}; SELECT x FROM ${CLICKHOUSE_DATABASE}.dist_04498 ORDER BY x SETTINGS prefer_localhost_replica=0"

# With role_admin the remote node should see all rows.
echo "-- role_admin via Distributed"
${CLICKHOUSE_CLIENT} --user "${USER}" -q "SET ROLE ${ROLE_ADMIN}; SELECT x FROM ${CLICKHOUSE_DATABASE}.dist_04498 ORDER BY x SETTINGS prefer_localhost_replica=0"

# Cleanup
${CLICKHOUSE_CLIENT} -q "DROP TABLE IF EXISTS ${CLICKHOUSE_DATABASE}.dist_04498"
${CLICKHOUSE_CLIENT} -q "DROP TABLE IF EXISTS ${CLICKHOUSE_DATABASE}.local_04498"
${CLICKHOUSE_CLIENT} -q "DROP ROW POLICY IF EXISTS pol_narrow_04498 ON ${CLICKHOUSE_DATABASE}.local_04498"
${CLICKHOUSE_CLIENT} -q "DROP ROW POLICY IF EXISTS pol_admin_04498 ON ${CLICKHOUSE_DATABASE}.local_04498"
${CLICKHOUSE_CLIENT} -q "DROP ROLE IF EXISTS ${ROLE_NARROW}"
${CLICKHOUSE_CLIENT} -q "DROP ROLE IF EXISTS ${ROLE_ADMIN}"
${CLICKHOUSE_CLIENT} -q "DROP USER IF EXISTS ${USER}"
